### ISSUE TITLE
Preferences selector is not working

### ISSUE THREAD

**Issue by guylepage3** [Monnoroch/ColorHighlighter#376]
I have installed Color Highlighter for Mac but when I go to Preferences > Package Settings > Color Highlighter I do not get any options other than 

```
Settings - Default
Settings - User
```
<img width="437" alt="screenshot 2017-10-01 16 34 49" src="https://user-images.githubusercontent.com/1711854/31058783-84d36f22-a6c7-11e7-98d3-ad2dfd2986ce.png">

In the instructions on your PackageControl.io page you state that there are dropdown flyout options to choose from. But I am not seeing them. How can I choose custom options?

**Comment by Monnoroch** [comment]
Thanks for the report! I've just fixed the settings path, should propagate to package control in an hour or so. As per README, there's a menu you can use instead of the settings file `Tools > Color Highlighter > ...`. It doens't support all the settings, but most of the settings one would want to configure.

**Comment by guylepage3** [comment]
Thanks @Monnoroch. I do not see that in your README. Can you provide more context please? Thank you.

**Comment by Monnoroch** [comment]
Sure, here's the section about configuring the plugin with a menu: https://github.com/Monnoroch/ColorHighlighter#color-highlighting-styles.

**Comment by guylepage3** [comment]
Thank you sir.

**Comment by Monnoroch** [comment]
Glad to help!
